server:
  port: 10002
spring:
  application:
    name: member-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          semaphore:
            maxConcurrnetRequests: 20  #信号量隔离时，默认最大请求书为20
#          thread:
#            timeoutInMilliseconds: 4000 #断路器超时时间，默认1000ms
#
config:
    server: aaaa



